"""add celebrity and face shape

Revision ID: 03dc2058090f
Revises: f6f7438aab96
Create Date: 2025-08-23 20:24:46.320808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03dc2058090f'
down_revision: Union[str, Sequence[str], None] = 'f6f7438aab96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celebrities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('picture_url', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('similarity_text', sa.Text(), nullable=False),
    sa.Column('faceshape_id', sa.UUID(), nullable=True),
    sa.Column('color_analysis_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('face_shapes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('penjelasan_face_shape', sa.Text(), nullable=False),
    sa.Column('karakteristik', sa.Text(), nullable=False),
    sa.Column('tips_bentuk_wajah', sa.Text(), nullable=False),
    sa.Column('illustration_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('face_shapes')
    op.drop_table('celebrities')
    # ### end Alembic commands ###
