"""add color user photo

Revision ID: 0fd92aac8d7c
Revises: e22b73a1afa1
Create Date: 2025-08-23 23:45:29.650640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fd92aac8d7c'
down_revision: Union[str, Sequence[str], None] = 'e22b73a1afa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('analysis_result_id', sa.UUID(), nullable=False),
    sa.Column('feedback_type', sa.Text(), nullable=False),
    sa.Column('feedback_comment', sa.Text(), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_bmi_compatibility',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('bmi_category_id', sa.UUID(), nullable=False),
    sa.Column('compatibility_score', sa.Integer(), nullable=False),
    sa.Column('compatibility_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_body_shape_compatibility',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('body_shape_id', sa.UUID(), nullable=False),
    sa.Column('compatibility_score', sa.Integer(), nullable=False),
    sa.Column('compatibility_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_color_analysis_compatibility',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_color_id', sa.UUID(), nullable=False),
    sa.Column('color_analysis_id', sa.UUID(), nullable=False),
    sa.Column('compatibility_score', sa.Integer(), nullable=False),
    sa.Column('compatibility_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_colors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('color_name', sa.Text(), nullable=False),
    sa.Column('hex_color', sa.Text(), nullable=False),
    sa.Column('color_image_url', sa.Text(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_analysis_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('face_shape_id', sa.UUID(), nullable=True),
    sa.Column('body_shape_id', sa.UUID(), nullable=True),
    sa.Column('color_analysis_id', sa.UUID(), nullable=True),
    sa.Column('bmi_category_id', sa.UUID(), nullable=True),
    sa.Column('celebrity_id', sa.UUID(), nullable=True),
    sa.Column('analysis_details', sa.JSON(), nullable=True),
    sa.Column('is_final_result', sa.Boolean(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_analysis_results')
    op.drop_table('product_colors')
    op.drop_table('product_color_analysis_compatibility')
    op.drop_table('product_body_shape_compatibility')
    op.drop_table('product_bmi_compatibility')
    op.drop_table('analysis_feedback')
    # ### end Alembic commands ###
