"""add BMI

Revision ID: 147f5baf5a25
Revises: 1dd47b23de81
Create Date: 2025-08-23 17:42:34.811235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '147f5baf5a25'
down_revision: Union[str, Sequence[str], None] = '1dd47b23de81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bmi_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kategori', sa.Text(), nullable=False),
    sa.Column('min_bmi', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('max_bmi', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('tips_fashion', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('bmi_tips_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bmi_categories')
    # ### end Alembic commands ###
