"""set last name to nullable

Revision ID: 37b451ee6cff
Revises: 329e9f25f364
Create Date: 2025-08-28 12:52:58.684387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37b451ee6cff'
down_revision: Union[str, Sequence[str], None] = '329e9f25f364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('face_shapes', 'face_tips_summary')
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('face_shapes', sa.Column('face_tips_summary', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
