"""initial user model

Revision ID: 5466b47503dc
Revises: ff77d38ae316
Create Date: 2025-08-06 14:43:50.233647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5466b47503dc'
down_revision: Union[str, Sequence[str], None] = 'ff77d38ae316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True, comment='nullable for non-Google users'))
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True, comment='nullable for Google users'))
    op.add_column('users', sa.Column('profile_picture_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email_verified_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'profile_picture_url')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###
