"""add body_shape

Revision ID: 6bbc1443487f
Revises: 147f5baf5a25
Create Date: 2025-08-23 19:53:47.317079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bbc1443487f'
down_revision: Union[str, Sequence[str], None] = '147f5baf5a25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_shapes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('penjelasan_body_shape', sa.Text(), nullable=False),
    sa.Column('karakteristik', sa.Text(), nullable=False),
    sa.Column('tips_body_shape', sa.Text(), nullable=False),
    sa.Column('link_picture', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('body_shapes')
    # ### end Alembic commands ###
