"""add color analysis

Revision ID: a9d15e94bc19
Revises: 03dc2058090f
Create Date: 2025-08-23 20:37:08.024680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9d15e94bc19'
down_revision: Union[str, Sequence[str], None] = '03dc2058090f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('penjelasan_color_analysis', sa.Text(), nullable=False),
    sa.Column('make_up_tips', sa.Text(), nullable=False),
    sa.Column('tips_warna_kulit_pakaian', sa.Text(), nullable=False),
    sa.Column('best_colour', sa.JSON(), nullable=False),
    sa.Column('worst_colour', sa.JSON(), nullable=False),
    sa.Column('neutral_colour', sa.JSON(), nullable=False),
    sa.Column('best_colour_combination', sa.JSON(), nullable=False),
    sa.Column('personality', sa.Text(), nullable=False),
    sa.Column('karakteristik', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('color_tips_summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('color_analysis')
    # ### end Alembic commands ###
