"""add all

Revision ID: c8471f969ea6
Revises: 0fd92aac8d7c
Create Date: 2025-08-24 00:31:50.428345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8471f969ea6'
down_revision: Union[str, Sequence[str], None] = '0fd92aac8d7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_face_shape_compatibility',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('face_shape_id', sa.UUID(), nullable=False),
    sa.Column('compatibility_score', sa.Integer(), nullable=False),
    sa.Column('compatibility_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_face_shape_compatibility')
    # ### end Alembic commands ###
