"""add color user photo

Revision ID: e22b73a1afa1
Revises: a9d15e94bc19
Create Date: 2025-08-23 20:58:57.555817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e22b73a1afa1'
down_revision: Union[str, Sequence[str], None] = 'a9d15e94bc19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_result_id', sa.UUID(), nullable=False),
    sa.Column('photo_type', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.Text(), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('analysis_metadata', sa.JSON(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_photos')
    # ### end Alembic commands ###
