"""add celebrity

Revision ID: f6f7438aab96
Revises: 6bbc1443487f
Create Date: 2025-08-23 20:13:47.920753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6f7438aab96'
down_revision: Union[str, Sequence[str], None] = '6bbc1443487f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('body_shapes', 'body_tips_summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('body_shapes', sa.Column('body_tips_summary', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
