version: "3.8"

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001" 
    environment:
      MINIO_ROOT_USER: minioadmin      
      MINIO_ROOT_PASSWORD: miniopassword 
      MINIO_MIN_FREE_DISK: 1G         
    volumes:
      - ./minio_data:/data  
    command: server /data --console-address ":9001"

volumes:
  minio_data:
