name: Deploy on Develop

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Trigger deployment
      run: |
        curl -X POST "http://62.72.29.121:3000/api/deploy/fa10b52bfa3cb485b2c775b28a2016c3f4032f7bfbb82d83" \
          -H "Content-Type: application/json" \
          --max-time 30 \
          --retry 3 \
          --retry-delay 5
        
    - name: Deployment status
      run: echo "Deployment webhook triggered successfully"